# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download keys
      run: |
        curl -o jihuoma.zip http://idea.medeming.com/jets/images/jihuoma.zip
    - name: Unzip
      run: |
        unzip jihuoma.zip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4
    - name: Run Application
      run: |
        python main.py
    - name: Preview index.html
      run: |
        cat dist/index.html
    - name: Deploy
      uses: saltbo/uptoc@master
      with:
        driver: qiniu
        region: cn-north-1
        bucket: jets-key
        dist: dist
      env:
        UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_AK }}
        UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_SK }}
